# Generated by Django 5.2.11 on 2026-02-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_is_paid_event_is_published_event_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
