# Generated by Django 5.2.11 on 2026-02-19 08:35

from django.db import migrations, models


def populate_total_events_created(apps, schema_editor):
    """Set total_events_created to current event count for existing profiles."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE api_eventownerprofile
            SET total_events_created = (
                SELECT COUNT(*) FROM api_event
                WHERE api_event.owner_id = api_eventownerprofile.user_id
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventownerprofile_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='total_events_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_total_events_created, migrations.RunPython.noop),
    ]
