# Generated by Django 5.2.11 on 2026-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_free_plan_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_per_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='event_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
