# Generated by Django 5.2.11 on 2026-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_paid_per_event_eventownerprofile_event_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventownerprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('per_event', 'Pay Per Event'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
