# Generated by Django 5.2.11 on 2026-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_per_event_plan_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerprofile',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventownerprofile',
            name='subscription_interval',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
